learninja/mentor/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, BooleanField
from wtforms.validators import DataRequired


class AddTopic(FlaskForm):
    course_add = StringField()
    subject_add = StringField()
    topic_add = StringField(validators=[DataRequired()])
    search = SubmitField('Add Topic')


class SearchTopic(FlaskForm):
    topic_search = StringField(validators=[DataRequired()])
    search = SubmitField('Search')
    add = SubmitField('Add')


class MentorAddTopic(FlaskForm):
    select_topic = BooleanField()
    add = SubmitField('Add')

learninja/student/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField
from wtforms.validators import DataRequired


class MentorSearch(FlaskForm):
    mentor_search = StringField(validators=[DataRequired()])
    search = SubmitField('Search')


class TopicSearch(FlaskForm):
    topic_search = StringField(validators=[DataRequired()])
    search = SubmitField('Search')


class AddTopic(FlaskForm):
    course_add = StringField()
    subject_add = StringField()
    topic_add = StringField(validators=[DataRequired()])
    search = SubmitField('Add')

learninja/account/views.py
from flask import render_template, url_for, flash, redirect, request, Blueprint, jsonify
from flask_login import login_user, current_user, logout_user, login_required
from learninja import db
from learninja.models import Users
from learninja.account.forms import SignupForm, LoginForm, ToggleMentorMode

users = Blueprint('users', __name__)


@users.route('/signup', methods=['GET', 'POST'])
def signup():
    form = SignupForm()

    if form.validate_on_submit():
        user = Users(username=form.username.data, email=form.email.data, password=form.password.data, user_type=1)
        db.session.add(user)
        db.session.commit()
        flash('Thanks for registering! Now you can login!')
        return redirect(url_for('users.login'))
    return render_template('signup.html', form=form)


@users.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm()
    if form.validate_on_submit():
        user = Users.query.filter_by(username=form.username.data).first()
        if user.check_password(form.password.data) and user is not None:
            login_user(user)
            flash('Logged in successfully.')

            # If a user was trying to visit a page that requires a login
            # flask saves that URL as 'next'.
            next = request.args.get('next')

            # So let's now check if that next exists, otherwise we'll go to
            # the welcome page.
            if next == None or not next[0] == '/':
                next = url_for('core.index')

            return redirect(url_for('users.profile'))
    return render_template('login.html', form=form)


@users.route('/profile', methods=['GET', 'POST'])
@login_required
def profile():
    form = ToggleMentorMode()
    if form.validate_on_submit():
        if current_user.user_type == 1:
            current_user.user_type = 2
            db.session.commit()
        else:
            current_user.user_type = 1
            db.session.commit()
    return render_template('profile.html', form=form)


@users.route("/logout")
def logout():
    logout_user()
    return redirect(url_for('core.index'))


@users.route('/become-mentor')
@login_required
def become_mentor():
    current_user.user_type = 2
    db.session.commit()
    return redirect(url_for('users.profile'))

@users.route('/test')
def test():
    return render_template('test.html', form=form)

learninja/mentor/views.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import login_required
from learninja import db, bp_student
from learninja.models import Topics
from learninja.mentor.forms import AddTopic, SearchTopic
import pandas as pd
import sqlite3


bp_mentor = Blueprint('bp_mentor', __name__)


@bp_mentor.route('/add-topic', methods=['GET', 'POST'])
def add_topic():
    form = AddTopic()
    course_add = subject_add = 'Other'
    topic_add = ''
    if form.validate_on_submit():
        if form.course_add.data:
            course_add = form.course_add.data
            if form.subject_add.data:
                subject_add = form.subject_add.data
        topic_add = form.topic_add.data
        add_topic_field = Topics(course=course_add, subject=subject_add, topic=topic_add)
        db.session.add(add_topic_field)
        db.session.commit()
        return redirect(url_for('bp_student.student'))
    return render_template('add-topic.html', form=form, course_add=course_add, subject_add=subject_add, topic_add=topic_add)


@bp_mentor.route('/mentor-profile', methods=['GET', 'POST'])
def mentor_profile():
    form = SearchTopic()
    topic_search = form.topic_search.data
    mentor_topic = Topics.query.filter_by(topic=topic_search).all()


    return render_template('mentor.html', form=form, mentor_topic=mentor_topic)

learninja/student/views.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import login_required
from learninja import db
from learninja.models import Topics
from learninja.student.forms import MentorSearch, TopicSearch

bp_student = Blueprint('bp_student', __name__)


@bp_student.route('/student', methods=['GET', 'POST'])
def student():
    form = TopicSearch()
    subject_topic = ''
    course_topic = ''
    if form.validate_on_submit():
        topic_search_field = Topics.query.filter_by(topic=form.topic_search.data).first()
        subject_topic = topic_search_field.subject
        course_topic = topic_search_field.course
    return render_template('student.html', form=form, subject_topic=subject_topic, course_topic=course_topic)


@bp_student.route('/mentor-search', methods=['GET', 'POST'])
def mentor_search():
    form = MentorSearch()
    return render_template('mentor-search.html', form=form)

learninja/templates/add-topic.html
{% extends 'base.html' %}
{% block content %}
<h1>Add Topic</h1>
<form method="POST">
{{ form.hidden_tag() }}
<div>
{{ form.topic_add(class='form-control', placeholder='Topic') }}
{{ form.subject_add(class='form-control', placeholder='Subject') }}
{{ form.course_add(class='form-control', placeholder='Course') }}
{{ form.search(class='btn btn-primary') }}
</div>
    </form>
{% endblock %}

learninja/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="content-type" content="text/html; charset=utf-8" />
	<meta name="author" content="SemiColonWeb" />
    <title>Learninja</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,400i,700|Istok+Web:400,700" rel="stylesheet" type="text/css" />
	<link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap.css')}}" type="text/css" />
	<link rel="stylesheet" href="{{ url_for('static', filename='css/style.css')}}" type="text/css" />

	<link rel="stylesheet" href="{{ url_for('static', filename='css/dark.css')}}" type="text/css" />
	<link rel="stylesheet" href="{{ url_for('static', filename='css/font-icons.css')}}" type="text/css" />
	<link rel="stylesheet" href="{{ url_for('static', filename='css/animate.css')}}" type="text/css" />
	<link rel="stylesheet" href="{{ url_for('static', filename='css/magnific-popup.css')}}" type="text/css" />

	<link rel="stylesheet" href="{{ url_for('static', filename='css/ion.rangeslider.css')}}" type="text/css" />

	<link rel="stylesheet" href="{{ url_for('static', filename='css/responsive.css')}}" type ="text/css" />
    <link rel="stylesheet" href="{{ url_for('static', filename='css/colors.css')}}" type="text/css" />

    <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
    <link rel="stylesheet" href="css/colors.php?color=44aaac" type="text/css" /> <!-- Theme Color -->
	<link rel="stylesheet" href="{{ url_for('static', filename='css/fonts.css')}}" type="text/css" />
	<link rel="stylesheet" href="{{ url_for('static', filename='css/hosting.css')}}" type="text/css" />
    <link rel="stylesheet" href="{{ url_for('static', filename='css/custom.css')}}" type="text/css" />

    <script src="{{ url_for('static', filename='js/jquery.js')}}"></script>
	<script src="{{ url_for('static', filename='js/plugins.js')}}"></script>

	<script src="{{ url_for('static', filename='js/jquery.hotspot.js')}}"></script>
	<script src="{{ url_for('static', filename='js/rangeslider.min.js')}}"></script>

    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    <script src="https://kit.fontawesome.com/b02df55fb5.js" crossorigin="anonymous"></script>
</head>
<body class = 'stretched'>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="/">Learninja</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a class="nav-link" href="/">Home</a>
      </li>

      <li class="nav-item">
        <a class="nav-link" href="/login">Log In</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/signup">Sign Up</a>
      </li>


      <li class="nav-item">
        <a class="nav-link" href="/become-mentor">Become a Mentor</a>
      </li>

      <li class="nav-item">
        <a class="nav-link" href="/student">Browse as Student</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/learn-more">Learn More</a>
      </li>

    </ul>
    </form>
  </div>
</nav>

{% block content %}
{% endblock %}
</body>
</html>

learninja/templates/index.html
{% extends 'base.html' %}
{% block content %}
<h1>Welcome to Learninja</h1>
    <h3>A platform built for students who want to learn and students who want to teach.</h3>
{% endblock %}

learninja/templates/learn-more.html
{% extends 'base.html' %}
{% block content %}
<h1>Learn more about Learninja</h1>
{% endblock %}

learninja/templates/login.html
{% extends 'base.html' %}
{% block content %}
<h1>Log In</h1>

    <form method="POST">
    {{ form.hidden_tag() }}
    {{ form.username(class="form-control", placeholder="Username") }}<br>
    {{ form.password(class="form-control", placeholder="Password") }}<br>
        <p>{{ form.submit(class="btn btn-primary") }}</p>
    </form>
    <p><a href="{{ url_for('users.signup') }}">Sign Up</a></p>
{% endblock %}

learninja/templates/mentor-search.html
{% extends 'base.html' %}
{% block content %}
    <form method="POST">
{{ form.mentor_search() }}
{{ form.search }}
    <p>{{ form.mentor_search.data }}</p>
    </form>
{% endblock %}

learninja/templates/mentor.html
{% extends 'base.html' %}
{% block content %}
<h1>Mentor Profile</h1>
<p>Search for topics you can Teach</p>
    <form method="POST">
    {{ form.hidden_tag() }}
    {{ form.topic_search(placeholder='Search for topic') }}
    {{ form.search(class='btn btn-primary') }}
    </form>
    <p>{{ course_list_unique }}</p>
    <p>{{ subject_list }}</p>
    <p>Course: {{ course }}</p>
    {% for topic in mentor_topic %}
    <p>{{ topic }}</p>
    {% endfor %}

{% endblock %}

learninja/templates/profile.html
{% extends 'base.html' %}
{% block content %}
<h1>Logged In</h1>
<p>Username: {{ current_user.username }}</p>
<p>Email: {{ current_user.email }}</p>
<form method="POST">
{{ form.hidden_tag() }}
{% if current_user.user_type == 0 %}
    <p>Account Type: Admin</p>
{% elif current_user.user_type == 1 %}
    <p>Mentor Mode: Off</p>
    <p>{{ form.submit(class="btn btn-primary", value="Activate Mentor Mode") }}</p>
    {% elif current_user.user_type == 2 %}
    <p>Mentor Mode: On</p>
    <p>{{ form.submit(class="btn btn-primary", value="Deactivate Mentor Mode") }}</p>
    {% elif current_user.user_type == 3 %}
    <p>Account Type: Student and Mentor</p>
{% else %}
    <p>There is some error: {{ current_user.user_type }}</p>
{% endif %}
<p><button type="button" class="btn btn-primary">Edit Profile</button></p>
{{ form.boolean_test(class="custom-control-input") }}
    </form>
{% endblock %}

learninja/templates/signup.html
{% extends 'base.html' %}
{% block content %}
<h1>Sign Up</h1>
    <form method="POST">
    {{ form.hidden_tag() }}
    {{ form.username() }}<br>
    {{ form.email() }}<br>
    {{ form.password() }}<br>
    {{ form.confirm_password() }}<br>
    {{ form.submit() }}
    </form>
{% endblock %}

learninja/templates/student.html
{% extends 'base.html' %}
{% block content %}
<form method="POST">
{{ form.hidden_tag() }}
<div>
{{ form.topic_search(class='form-control', placeholder='Search for Course, Subject or Topic') }}
{{ form.search(class='btn btn-primary') }}
    <p>{{ form.topic_search.data }}</p>
    <p>{{ subject_topic }}</p>
    <p>{{ course_topic }}</p>
</div>
    </form>
{% endblock %}

learninja/templates/test.html
{% extends 'base.html' %}
{% block content %}
<h1>test</h1>
    <div class="custom-control custom-switch">
  <input type="checkbox" class="custom-control-input" id="customSwitch1">
  <label class="custom-control-label" for="customSwitch1">Toggle this switch element</label>
</div>
    <div class="just-padding">

<div class="list-group list-group-root well">

  <a href="#item-1" class="list-group-item" data-toggle="collapse">
    <i class="glyphicon glyphicon-chevron-right"></i>Item 1
  </a>
  <div class="list-group collapse" id="item-1">

    <a href="#item-1-1" class="list-group-item" data-toggle="collapse">
      <i class="glyphicon glyphicon-chevron-right"></i>Item 1.1
    </a>
    <div class="list-group collapse" id="item-1-1">
      <emsb><a href="#" class="list-group-item">Item 1.1.1</a></emsb>
      <a href="#" class="list-group-item">Item 1.1.2</a>
      <a href="#" class="list-group-item">Item 1.1.3</a>
    </div>

    <a href="#item-1-2" class="list-group-item" data-toggle="collapse">
      <i class="glyphicon glyphicon-chevron-right"></i>Item 1.2
    </a>
    <div class="list-group collapse" id="item-1-2">
      <a href="#" class="list-group-item">Item 1.2.1</a>
      <a href="#" class="list-group-item">Item 1.2.2</a>
      <a href="#" class="list-group-item">Item 1.2.3</a>
    </div>

    <a href="#item-1-3" class="list-group-item" data-toggle="collapse">
      <i class="glyphicon glyphicon-chevron-right"></i>Item 1.3
    </a>
    <div class="list-group collapse" id="item-1-3">
      <a href="#" class="list-group-item">Item 1.3.1</a>
      <a href="#" class="list-group-item">Item 1.3.2</a>
      <a href="#" class="list-group-item">Item 1.3.3</a>
    </div>

  </div>

  <a href="#item-2" class="list-group-item" data-toggle="collapse">
    <i class="glyphicon glyphicon-chevron-right"></i>Item 2
  </a>
  <div class="list-group collapse" id="item-2">

    <a href="#item-2-1" class="list-group-item" data-toggle="collapse">
      <i class="glyphicon glyphicon-chevron-right"></i>Item 2.1
    </a>
    <div class="list-group collapse" id="item-2-1">
      <a href="#" class="list-group-item">Item 2.1.1</a>
      <a href="#" class="list-group-item">Item 2.1.2</a>
      <a href="#" class="list-group-item">Item 2.1.3</a>
    </div>

    <a href="#item-2-2" class="list-group-item" data-toggle="collapse">
      <i class="glyphicon glyphicon-chevron-right"></i>Item 2.2
    </a>
    <div class="list-group collapse" id="item-2-2">
      <a href="#" class="list-group-item">Item 2.2.1</a>
      <a href="#" class="list-group-item">Item 2.2.2</a>
      <a href="#" class="list-group-item">Item 2.2.3</a>
    </div>

    <a href="#item-2-3" class="list-group-item" data-toggle="collapse">
      <i class="glyphicon glyphicon-chevron-right"></i>Item 2.3
    </a>
    <div class="list-group collapse" id="item-2-3">
      <a href="#" class="list-group-item">Item 2.3.1</a>
      <a href="#" class="list-group-item">Item 2.3.2</a>
      <a href="#" class="list-group-item">Item 2.3.3</a>
    </div>

  </div>


  <a href="#item-3" class="list-group-item" data-toggle="collapse">
    <i class="glyphicon glyphicon-chevron-right"></i>Item 3
  </a>
  <div class="list-group collapse" id="item-3">

    <a href="#item-3-1" class="list-group-item" data-toggle="collapse">
      <i class="glyphicon glyphicon-chevron-right"></i>Item 3.1
    </a>
    <div class="list-group collapse" id="item-3-1">
      <a href="#" class="list-group-item">Item 3.1.1</a>
      <a href="#" class="list-group-item">Item 3.1.2</a>
      <a href="#" class="list-group-item">Item 3.1.3</a>
    </div>

    <a href="#item-3-2" class="list-group-item" data-toggle="collapse">
      <i class="glyphicon glyphicon-chevron-right"></i>Item 3.2
    </a>
    <div class="list-group collapse" id="item-3-2">
      <a href="#" class="list-group-item">Item 3.2.1</a>
      <a href="#" class="list-group-item">Item 3.2.2</a>
      <a href="#" class="list-group-item">Item 3.2.3</a>
    </div>

    <a href="#item-3-3" class="list-group-item" data-toggle="collapse">
      <i class="glyphicon glyphicon-chevron-right"></i>Item 3.3
    </a>
    <div class="list-group collapse" id="item-3-3">
      <a href="#" class="list-group-item">Item 3.3.1</a>
      <a href="#" class="list-group-item">Item 3.3.2</a>
      <a href="#" class="list-group-item">Item 3.3.3</a>
    </div>

  </div>

</div>

</div>


    <p>
  <a class="btn btn-primary" data-toggle="collapse" href="#collapseExample" role="button" aria-expanded="false" aria-controls="collapseExample">
    Link with href
  </a>
  <button class="btn btn-primary" type="button" data-toggle="collapse" data-target="#collapseExample" aria-expanded="false" aria-controls="collapseExample">
    Button with data-target
  </button>
</p>
<div class="collapse" id="collapseExample">
  <div class="card card-body">
    Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. Nihil anim keffiyeh helvetica, craft beer labore wes anderson cred nesciunt sapiente ea proident.
  </div>
</div>

    <div class="form-widget">
	<div class="form-result"></div>

	<form class="row" id="template-contactform" action="include/form.php" method="post">

		<div class="form-process"></div>

		<div class="col-md-6 form-group">
			<label for="template-contactform-name">Name <small>*</small></label>
			<input type="text" id="template-contactform-name" name="template-contactform-name" value="" class="form-control required" />
		</div>

		<div class="col-md-6 form-group">
			<label for="template-contactform-email">Email <small>*</small></label>
			<input type="email" id="template-contactform-email" name="template-contactform-email" value="" class="required email form-control" />
		</div>

		<div class="w-100"></div>

		<div class="col-12 form-group">
			<label for="template-contactform-message">Message <small>*</small></label>
			<textarea class="required form-control" id="template-contactform-message" name="template-contactform-message" rows="6" cols="30"></textarea>
		</div>

		<div class="col-12 hidden">
			<input type="text" id="template-contactform-botcheck" name="template-contactform-botcheck" value="" class="form-control" />
		</div>

		<div class="col-12">
			<button class="button button-3d nomargin" type="submit" id="template-contactform-submit" name="template-contactform-submit" value="submit">Send Message</button>
		</div>

		<!-- Form Settings -->

		<input type="hidden" name="prefix" value="template-contactform-">
		<input type="hidden" name="subject" value="Message from Contact Form">

	</form>
</div>
{% endblock %}